name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            if redis-cli ping; then
              echo "Redis is ready";
              break;
            else
              echo "Waiting for Redis to start...";
              sleep 2;
            fi
          done

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
